### ISSUE TITLE
Detection of newest ColdFusion 11

### ISSUE THREAD

**Issue by infosec-au** [hatRiot/clusterd#35]
Hi there,

Doing some testing on CF 11, seems that clusterd does not identify the coldfusion installation successfully. Since it compares image hashes, I have uploaded this image here.

MD5 (loginbackground.jpg) = 457c6f1f26d8a030a9301e975663589d

![loginbackground](https://cloud.githubusercontent.com/assets/5241936/5994022/f38679e0-aab8-11e4-809f-fd7820f9a5d9.jpg)

**Comment by infosec-au** [comment]
Additionally, here are the server details regarding my ColdFusion installation:

```Server Product	ColdFusion
Version	11,0,03,292480
Edition	Developer  
Operating System	Mac OS X
```

**Comment by hatRiot** [comment]
Thanks for this info!  The last time I tested CF11 was during beta, so it's likely that things have changed.  I'll get this updated and close this once it's in dev.

**Comment by hatRiot** [comment]
Tested and pushed to dev, thanks again!
