### ISSUE TITLE
Can I try on Win 7 ?

### ISSUE THREAD

**Issue by pedrodj** [hatRiot/clusterd#51]
Hi.

hatRiot, thank for your work!

$ pip install -r requirements.txt
Requirement already satisfied: requests>=2.2.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: idna<2.6,>=2.5 in c:\python27\lib\site-packages (from requests>=2.2.1->-r requirements.txt (line 1))
Requirement already satisfied: urllib3<1.22,>=1.21.1 in c:\python27\lib\site-packages (from requests>=2.2.1->-r requirements.txt (line 1))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python27\lib\site-packages (from requests>=2.2.1->-r requirements.txt (line 1))
Requirement already satisfied: certifi>=2017.4.17 in c:\python27\lib\site-packages (from requests>=2.2.1->-r requirements.txt (line 1))

Pedro@Pedro-PC MINGW64 /e/Python27/clusterd (master)
$ python clusterd.py -i x.x.x.x

                clusterd/0.5 - clustered attack toolkit
                        [Supporting 7 platforms]

[2018-03-13 08:55PM] Started at 2018-03-13 08:55PM
Traceback (most recent call last):
  File "clusterd.py", line 121, in <module>
    prerun(options)
  File "clusterd.py", line 45, in prerun
    mkdir(state.serve_dir)
WindowsError: [Error 3] Impossibile trovare il percorso specificato: '/tmp/.clusterd'

**Comment by hatRiot** [comment]
This has not been tested on Windows and there are currently no plans to add support for it. I will accept PRs for it, though.
